env = "dev"

[server]
port = 2020
ip = "0.0.0.0"

# ui manager properties
[ui]
secret = "${env:CMS_UI_SECRET}"	  # secret for JWT

[ipc]
port = 6868
password = "test_pwd"

[modules]
#active = ["backup-server-module"]
